import { mkdir, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';
import { build } from 'esbuild';
import type { BundleStageInput, BundleResult, BundleStager } from './types.js';

/**
 * Versioned identifier embedded in the generated runner so a future
 * bundle reader can detect format drift. Bumped whenever the runner
 * shape changes incompatibly.
 */
const RUNNER_FORMAT_VERSION = 1;

/**
 * Stage a deploy-ready bundle to `input.outDir`. Output layout:
 *
 *   <outDir>/
 *     agent.bundle.mjs       — esbuilt user `onEvent` (default-exported handler)
 *     runner.mjs             — entry that imports the runtime + bundle + persona
 *     persona.json           — verbatim copy of the input persona spec
 *     package.json           — minimal manifest pinning the runtime dep
 *
 * The bundle is idempotent: re-running with the same `outDir` overwrites
 * the four files cleanly. Auxiliary files left behind from earlier runs
 * are not touched (callers control the directory lifecycle).
 *
 * Externals: every `node:*` builtin and `@agentworkforce/runtime` itself
 * are left external so the runner can resolve them at execution time.
 * Bundling the runtime in would require shipping the runtime sources into
 * every sandbox; the chosen split keeps the bundle small and lets ops
 * patch the runtime without rebuilding every persona.
 */
export const bundleStager: BundleStager = {
  async stage(input: BundleStageInput): Promise<BundleResult> {
    await mkdir(input.outDir, { recursive: true });

    const onEventAbs = path.resolve(path.dirname(input.personaPath), input.persona.onEvent ?? '');
    if (!input.persona.onEvent) {
      throw new Error(
        `bundle: persona "${input.persona.id}" is missing onEvent (cannot stage a bundle without a handler)`
      );
    }
    await assertReadableFile(onEventAbs, `persona "${input.persona.id}" onEvent`);

    const bundlePath = path.join(input.outDir, 'agent.bundle.mjs');
    const runnerPath = path.join(input.outDir, 'runner.mjs');
    const personaCopyPath = path.join(input.outDir, 'persona.json');
    const packageJsonPath = path.join(input.outDir, 'package.json');

    await build({
      entryPoints: [onEventAbs],
      outfile: bundlePath,
      bundle: true,
      format: 'esm',
      platform: 'node',
      target: 'node20',
      sourcemap: 'inline',
      logLevel: 'silent',
      minify: input.bundlerOptions?.minify ?? false,
      // Resolve TypeScript / JS extensions without forcing the user to
      // write `.ts`-suffixed imports in their handler file.
      resolveExtensions: ['.ts', '.mts', '.cts', '.tsx', '.js', '.mjs', '.cjs', '.jsx', '.json'],
      external: [
        // Runtime stays external — see file header comment.
        '@agentworkforce/runtime',
        '@agentworkforce/runtime/raw',
        // Node builtins must never be bundled.
        'node:*'
      ]
    });

    await writeFile(personaCopyPath, JSON.stringify(input.persona, null, 2) + '\n', 'utf8');

    await writeFile(packageJsonPath, buildPackageJson(input.persona.id), 'utf8');

    await writeFile(runnerPath, renderRunner(), 'utf8');

    const bundleStat = await stat(bundlePath);
    const runnerStat = await stat(runnerPath);
    const sizeBytes = bundleStat.size + runnerStat.size;

    return {
      personaCopyPath,
      runnerPath,
      bundlePath,
      packageJsonPath,
      sizeBytes
    };
  }
};

function buildPackageJson(personaId: string): string {
  return (
    JSON.stringify(
      {
        name: `@agentworkforce/deployed-${personaId}`,
        private: true,
        version: '0.0.0',
        type: 'module',
        main: './runner.mjs',
        dependencies: {
          '@agentworkforce/runtime': '*'
        },
        comment:
          'Generated by workforce deploy. The runtime dep is pinned to "*" because deploys resolve the runtime version from the active workspace.'
      },
      null,
      2
    ) + '\n'
  );
}

function renderRunner(): string {
  return `// Generated by @agentworkforce/deploy. Format version ${RUNNER_FORMAT_VERSION}.
// Do not edit by hand — \`workforce deploy\` overwrites this file on every stage.
//
// The runner imports the user's handler from the esbuilt bundle, the
// parsed persona spec from the verbatim JSON copy, and the runtime's
// \`startRunner\` to drive the dispatch loop. Envelopes arrive on stdin
// as NDJSON; structured logs go to stdout.

import { createRequire } from 'node:module';
import { startRunner } from '@agentworkforce/runtime/runner';
import { handler as wrapHandler } from '@agentworkforce/runtime';
import * as userModule from './agent.bundle.mjs';

const require = createRequire(import.meta.url);
const persona = require('./persona.json');

const candidate = userModule.default ?? userModule.handler;
if (typeof candidate !== 'function') {
  throw new TypeError(
    \`workforce deploy bundle: \${persona.id} did not default-export a function. Did you forget \\\`export default handler(...)\\\`?\`
  );
}
const handler = candidate.__workforceHandler ? candidate : wrapHandler(candidate);

await startRunner({ persona, handler });
`;
}

async function assertReadableFile(abs: string, label: string): Promise<void> {
  try {
    const st = await stat(abs);
    if (!st.isFile()) {
      throw new Error(`${label}: ${abs} is not a regular file`);
    }
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') {
      throw new Error(`${label}: file not found at ${abs}`);
    }
    throw err;
  }
}
