// Generates `src/generated/clients.ts` — a named resource-keyed client for
// every provider in the writeback-path catalog. Run after bumping
// `@relayfile/adapter-core`:
//
//   pnpm --filter @agentworkforce/relay-helpers gen
//
// `renderClients()` is also imported by the in-sync test, so a stale committed
// file fails CI.
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { WRITEBACK_PATH_CATALOG } from '@relayfile/adapter-core/writeback-paths';

/** Providers with a bespoke, hand-written client module (enriched with named methods). */
export const BESPOKE_PROVIDERS = new Set(['linear', 'github', 'slack']);

const camel = (slug) => slug.replace(/-([a-z])/g, (_m, c) => c.toUpperCase());
export const clientName = (provider) => `${camel(provider)}Client`;

/** Catalog providers that get a generated (non-bespoke) client, sorted. */
export function generatedProviders() {
  return Object.keys(WRITEBACK_PATH_CATALOG)
    .filter((provider) => !BESPOKE_PROVIDERS.has(provider))
    .sort();
}

export function renderClients() {
  const header =
    `// GENERATED by scripts/generate-clients.mjs from\n` +
    `// @relayfile/adapter-core/writeback-paths — do not edit by hand.\n` +
    `// Run \`pnpm --filter @agentworkforce/relay-helpers gen\` after bumping adapter-core.\n` +
    `//\n` +
    `// linear / github / slack have bespoke ergonomic clients in their own modules;\n` +
    `// every other catalog provider gets a uniform resource-keyed client here.\n`;
  const imports =
    `import type { IntegrationClientOptions } from '@agentworkforce/runtime/clients';\n` +
    `import { providerClient, type ProviderClient } from '../provider-client.js';\n`;
  const body = generatedProviders()
    .map(
      (provider) =>
        `export const ${clientName(provider)} = (opts?: IntegrationClientOptions): ProviderClient<'${provider}'> =>\n` +
        `  providerClient('${provider}', opts);`
    )
    .join('\n\n');
  return `${header}\n${imports}\n${body}\n`;
}

const outputFile = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../src/generated/clients.ts'
);

// Write when executed directly (`node scripts/generate-clients.mjs`).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  await writeFile(outputFile, renderClients());
  process.stdout.write(`wrote ${path.relative(process.cwd(), outputFile)} (${generatedProviders().length} clients)\n`);
}
