import type { IntegrationSource, PersonaInputSpec, PersonaSpec } from './types.js';

/**
 * Derive what a deployer must provide to stand up a persona, read DIRECTLY
 * from the persona definition — the single source of truth. There is no
 * separate manifest: a persona authored as `persona.ts` (via `definePersona`)
 * compiles to `persona.json` → {@link PersonaSpec}, and that parsed spec is the
 * runtime artifact loaders and the deploy CLI already read.
 *
 * One-click Layer-A deploy (into the existing shared platform) consumes this to
 * show the deployer exactly what's needed: which integrations to CONNECT and
 * which inputs to SUPPLY. Platform SST secrets are NOT a Layer-A concern (the
 * shared platform already has them) — `platformSecrets` is empty for Layer A.
 *
 * @see PersonaIntegrationConfig.optional (`required = !optional`)
 */

/** An integration the deployer must connect before the agent can fire. */
export interface RequiredIntegration {
  provider: string;
  /** Persona-declared source (defaults to `deployer_user` at parse time). */
  source?: IntegrationSource;
  /** `false` when the persona marks the integration `optional`. */
  required: boolean;
  /** Trigger event names declared on the persona for this provider. */
  triggers: string[];
}

/** A persona input the deployer must supply a value for. */
export interface RequiredInput {
  name: string;
  required: boolean;
  description?: string;
  /** Env var the launcher reads when no explicit value is given. */
  env?: string;
}

/**
 * A platform SST secret to seed — relevant to a Layer-B (`--isolated`) deploy
 * only. Empty for a Layer-A (shared-platform) deploy.
 */
export interface RequiredPlatformSecret {
  name: string;
  required: boolean;
  reason?: string;
  provider?: string;
}

/**
 * Credential backend an integration provider resolves through. Drives which
 * platform SST secrets an isolated stage must seed for that provider.
 */
export type IntegrationBackend = 'nango' | 'composio';

/**
 * Platform SST secrets a freshly-seeded isolated stage needs, keyed by the
 * provider's credential BACKEND (NOT a per-provider hand-list — that drifts
 * from the real provider registry; see the original wf#142 review). Salvaged
 * from the dropped AgentManifest path.
 *
 *  - `nango`    → resolve per-workspace creds via Nango + mint a relayfile
 *                 token via RelayAuth. (github/slack/linear/notion/jira/gmail/
 *                 dropbox and every other Nango-backed provider.)
 *  - `composio` → resolve creds via Composio (NOT Nango) + relayfile token.
 *
 * The RS256 relayauth signing keypair (`RelayauthSigningKeyPem`/`Public`) is
 * GENERATED by the seed script, not prompted, so it is deliberately absent.
 */
export const PLATFORM_SECRETS_BY_BACKEND: Readonly<
  Record<IntegrationBackend, readonly string[]>
> = {
  nango: ['NangoSecretKey', 'WebRelayauthApiKey'],
  composio: ['ComposioApiKey', 'WebRelayauthApiKey'],
};

/**
 * Extra platform secret for providers that fill a Nango webhook gap via
 * Hookdeck (e.g. GitLab) — layered ON TOP of the backend secrets.
 */
export const WEBHOOK_GAP_PLATFORM_SECRET = 'HookdeckSigningSecret';

export interface DeriveDeployRequirementsOptions {
  /**
   * Layer-B: compute `platformSecrets`. Layer-A (default) leaves them empty —
   * the shared platform already has these secrets.
   */
  isolated?: boolean;
  /**
   * Resolve a provider slug to its credential backend. persona-kit can't know
   * the full provider→backend map (that registry lives in the cloud app), so
   * the cloud caller INJECTS it; the default treats every provider as `nango`
   * (correct for all current first-party providers). This keeps the mapping
   * registry-derived rather than a drift-prone hand-list.
   */
  resolveBackend?: (provider: string) => IntegrationBackend;
  /** Whether a provider fills a Nango webhook gap via Hookdeck (e.g. gitlab). */
  isWebhookGapProvider?: (provider: string) => boolean;
}

export interface DeployRequirements {
  /**
   * Layer A: integrations to CONNECT (the deployer's only "real" prompt on the
   * shared platform). `required` integrations block the deploy until connected;
   * `optional` ones are surfaced but non-blocking.
   */
  integrations: RequiredIntegration[];
  /** Persona inputs the deployer must supply (no `default`, not `optional`). */
  inputs: RequiredInput[];
  /** Human-facing summary of what the deployed agent fires on. */
  firesOn: string[];
  /**
   * Layer-B (`--isolated`) ONLY: platform SST secrets to seed, derived from
   * each declared provider's backend via {@link PLATFORM_SECRETS_BY_BACKEND}.
   * Always empty for a Layer-A shared-platform deploy.
   */
  platformSecrets: RequiredPlatformSecret[];
}

/**
 * Read a persona's declared integrations / inputs / schedules / watches and
 * derive the deploy requirements. Pure function over {@link PersonaSpec}.
 *
 * @param persona the parsed persona spec (runtime artifact)
 * @param opts see {@link DeriveDeployRequirementsOptions}
 */
export function deriveDeployRequirements(
  persona: PersonaSpec,
  opts: DeriveDeployRequirementsOptions = {},
): DeployRequirements {
  const integrations: RequiredIntegration[] = Object.entries(
    persona.integrations ?? {},
  )
    .map(([provider, cfg]) => ({
      provider,
      ...(cfg.source ? { source: cfg.source } : {}),
      required: !cfg.optional,
      triggers: (cfg.triggers ?? []).map((t) => t.on),
    }))
    .sort((a, b) => a.provider.localeCompare(b.provider));

  const inputs: RequiredInput[] = Object.entries(
    (persona.inputs ?? {}) as Record<string, PersonaInputSpec>,
  )
    .filter(([, spec]) => spec.default === undefined && !spec.optional)
    .map(([name, spec]) => ({
      name,
      required: true,
      ...(spec.description ? { description: spec.description } : {}),
      ...(spec.env ? { env: spec.env } : {}),
    }))
    .sort((a, b) => a.name.localeCompare(b.name));

  const firesOn: string[] = [];
  for (const integration of integrations) {
    for (const event of integration.triggers) {
      firesOn.push(`${integration.provider}:${event}`);
    }
  }
  for (const schedule of persona.schedules ?? []) {
    firesOn.push(`schedule:${schedule.name}`);
  }
  for (const rule of persona.watch ?? []) {
    for (const event of rule.events ?? []) {
      firesOn.push(`relayfile:${event}`);
    }
  }

  return {
    integrations,
    inputs,
    firesOn: [...new Set(firesOn)],
    platformSecrets: opts.isolated
      ? derivePlatformSecrets(integrations, opts)
      : [],
  };
}

/**
 * Layer-B platform-secret derivation: union the backend secrets for each
 * declared provider (+ the Hookdeck webhook-gap secret where applicable),
 * deduped. Default backend = `nango`; the cloud caller injects `resolveBackend`
 * / `isWebhookGapProvider` from its provider registry for composio/gitlab.
 */
function derivePlatformSecrets(
  integrations: RequiredIntegration[],
  opts: DeriveDeployRequirementsOptions,
): RequiredPlatformSecret[] {
  const resolveBackend = opts.resolveBackend ?? (() => 'nango' as const);
  const isWebhookGap = opts.isWebhookGapProvider ?? (() => false);
  const seen = new Map<string, RequiredPlatformSecret>();

  for (const { provider } of integrations) {
    const backend = resolveBackend(provider);
    const names = [...PLATFORM_SECRETS_BY_BACKEND[backend]];
    if (isWebhookGap(provider)) {
      names.push(WEBHOOK_GAP_PLATFORM_SECRET);
    }
    for (const name of names) {
      if (!seen.has(name)) {
        seen.set(name, {
          name,
          required: true,
          reason: `required for the ${provider} integration (${backend}) to function`,
          provider,
        });
      }
    }
  }

  return [...seen.values()].sort((a, b) => a.name.localeCompare(b.name));
}
