/**
 * Vendored from @relayfile/adapter-core's generated trigger catalog.
 * Regenerate with `pnpm --filter @agentworkforce/persona-kit sync:known-triggers`.
 *
 * Event names are emitted verbatim from adapter supportedEvents() methods or
 * mapping.yaml webhooks keys. Do not normalize names across providers: the
 * cloud runtime matches persona triggers against each adapter's real event.type.
 */

export const KNOWN_TRIGGER_CATALOG = {
  "airtable": [
    "base.create",
    "base.delete",
    "base.update",
    "record.create",
    "record.delete",
    "record.update",
    "table.create",
    "table.delete",
    "table.update"
  ],
  "asana": [
    "project.added",
    "project.changed",
    "project.deleted",
    "project.removed",
    "section.added",
    "section.changed",
    "section.deleted",
    "section.removed",
    "task.added",
    "task.changed",
    "task.completed",
    "task.deleted",
    "task.removed",
    "workspace.added",
    "workspace.changed",
    "workspace.deleted",
    "workspace.removed"
  ],
  "calendly": [
    "event_type.canceled",
    "event_type.created",
    "event_type.deleted",
    "event_type.updated",
    "invitee.canceled",
    "invitee.created",
    "invitee.deleted",
    "invitee.updated",
    "scheduled_event.canceled",
    "scheduled_event.created",
    "scheduled_event.deleted",
    "scheduled_event.updated"
  ],
  "clickup": [
    "folder.created",
    "folder.deleted",
    "folder.updated",
    "list.created",
    "list.deleted",
    "list.updated",
    "space.created",
    "space.deleted",
    "space.updated",
    "task.created",
    "task.deleted",
    "task.updated"
  ],
  "confluence": [
    "page.created",
    "page.deleted",
    "page.updated",
    "space.created",
    "space.deleted",
    "space.updated"
  ],
  "github": [
    "check_run.completed",
    "issues.closed",
    "issues.opened",
    "pull_request.closed",
    "pull_request.opened",
    "pull_request.synchronize",
    "pull_request_review.submitted",
    "pull_request_review_comment.created"
  ],
  "gitlab": [
    "build.canceled",
    "build.created",
    "build.failed",
    "build.manual",
    "build.pending",
    "build.running",
    "build.skipped",
    "build.success",
    "deployment.canceled",
    "deployment.created",
    "deployment.failed",
    "deployment.running",
    "deployment.success",
    "issue.close",
    "issue.open",
    "issue.reopen",
    "issue.update",
    "job.canceled",
    "job.created",
    "job.failed",
    "job.manual",
    "job.pending",
    "job.running",
    "job.skipped",
    "job.success",
    "merge_request.approved",
    "merge_request.close",
    "merge_request.merge",
    "merge_request.open",
    "merge_request.reopen",
    "merge_request.unapproved",
    "merge_request.update",
    "note.Commit",
    "note.Issue",
    "note.MergeRequest",
    "note.Snippet",
    "pipeline.canceled",
    "pipeline.created",
    "pipeline.failed",
    "pipeline.manual",
    "pipeline.pending",
    "pipeline.running",
    "pipeline.skipped",
    "pipeline.success",
    "pipeline.waiting_for_resource",
    "push",
    "tag_push"
  ],
  "google-calendar": [
    "calendar.exists",
    "calendar.not_exists",
    "calendar.sync"
  ],
  "hubspot": [
    "company.associationChange",
    "company.created",
    "company.deleted",
    "company.merged",
    "company.propertyChange",
    "contact.associationChange",
    "contact.created",
    "contact.deleted",
    "contact.merged",
    "contact.propertyChange",
    "deal.associationChange",
    "deal.created",
    "deal.deleted",
    "deal.merged",
    "deal.propertyChange",
    "ticket.associationChange",
    "ticket.created",
    "ticket.deleted",
    "ticket.merged",
    "ticket.propertyChange"
  ],
  "intercom": [
    "company.archived",
    "company.closed",
    "company.created",
    "company.deleted",
    "company.reopened",
    "company.updated",
    "contact.archived",
    "contact.closed",
    "contact.created",
    "contact.deleted",
    "contact.reopened",
    "contact.updated",
    "conversation.archived",
    "conversation.closed",
    "conversation.created",
    "conversation.deleted",
    "conversation.reopened",
    "conversation.updated"
  ],
  "jira": [
    "comment.created",
    "comment.deleted",
    "comment.updated",
    "issue.created",
    "issue.deleted",
    "issue.updated",
    "project.created",
    "project.deleted",
    "project.updated",
    "sprint.created",
    "sprint.deleted",
    "sprint.updated"
  ],
  "linear": [
    "comment.create",
    "comment.remove",
    "comment.update",
    "cycle.create",
    "cycle.remove",
    "cycle.update",
    "issue.create",
    "issue.remove",
    "issue.update",
    "milestone.create",
    "milestone.remove",
    "milestone.update",
    "project.create",
    "project.remove",
    "project.update",
    "roadmap.create",
    "roadmap.remove",
    "roadmap.update"
  ],
  "mailgun": [
    "event.accepted",
    "event.clicked",
    "event.complained",
    "event.delivered",
    "event.failed",
    "event.opened",
    "event.permanent_fail",
    "event.stored",
    "event.unsubscribed",
    "list.created",
    "list.updated",
    "message.accepted",
    "message.delivered",
    "message.failed",
    "message.stored"
  ],
  "mixpanel": [
    "cohort.create",
    "cohort.delete",
    "cohort.merge",
    "cohort.update",
    "event.create",
    "event.delete",
    "event.merge",
    "event.update",
    "profile.create",
    "profile.delete",
    "profile.merge",
    "profile.update"
  ],
  "pipedrive": [
    "activity.created",
    "activity.deleted",
    "activity.updated",
    "deal.created",
    "deal.deleted",
    "deal.lost",
    "deal.updated",
    "deal.won",
    "organization.created",
    "organization.deleted",
    "organization.updated",
    "person.created",
    "person.deleted",
    "person.updated"
  ],
  "salesforce": [
    "Account.created",
    "Account.deleted",
    "Account.updated",
    "Account.upserted",
    "Case.closed",
    "Case.created",
    "Case.deleted",
    "Case.updated",
    "Case.upserted",
    "Contact.created",
    "Contact.deleted",
    "Contact.updated",
    "Contact.upserted",
    "Lead.converted",
    "Lead.created",
    "Lead.deleted",
    "Lead.updated",
    "Lead.upserted",
    "Opportunity.created",
    "Opportunity.deleted",
    "Opportunity.updated",
    "Opportunity.upserted"
  ],
  "segment": [
    "group.create",
    "group.update",
    "group.upsert",
    "identify.create",
    "identify.update",
    "identify.upsert",
    "page.create",
    "page.update",
    "page.upsert",
    "track.create",
    "track.update",
    "track.upsert"
  ],
  "sendgrid": [
    "contact.create",
    "contact.delete",
    "contact.update",
    "event.bounce",
    "event.click",
    "event.deferred",
    "event.delivered",
    "event.dropped",
    "event.group_resubscribe",
    "event.group_unsubscribe",
    "event.open",
    "event.processed",
    "event.spamreport",
    "event.unsubscribe",
    "mail.create",
    "mail.delete",
    "mail.update"
  ],
  "shopify": [
    "customer.cancel",
    "customer.create",
    "customer.delete",
    "customer.fulfill",
    "customer.paid",
    "customer.update",
    "fulfillment.cancel",
    "fulfillment.create",
    "fulfillment.delete",
    "fulfillment.fulfill",
    "fulfillment.paid",
    "fulfillment.update",
    "order.cancel",
    "order.create",
    "order.delete",
    "order.fulfill",
    "order.paid",
    "order.update",
    "product.cancel",
    "product.create",
    "product.delete",
    "product.fulfill",
    "product.paid",
    "product.update"
  ],
  "slack": [
    "channel.archived",
    "channel.created",
    "channel.deleted",
    "channel.member_joined",
    "channel.member_left",
    "channel.renamed",
    "channel.unarchived",
    "group.archived",
    "group.deleted",
    "group.renamed",
    "group.unarchived",
    "message.created",
    "message.deleted",
    "message.updated",
    "reaction.added",
    "reaction.removed",
    "user.changed",
    "user.joined"
  ],
  "stripe": [
    "charge.failed",
    "charge.refunded",
    "charge.succeeded",
    "charge.updated",
    "customer.created",
    "customer.deleted",
    "customer.subscription.created",
    "customer.subscription.deleted",
    "customer.subscription.updated",
    "customer.updated",
    "invoice.created",
    "invoice.finalized",
    "invoice.paid",
    "invoice.payment_failed",
    "invoice.updated",
    "invoice.voided",
    "payment_intent.canceled",
    "payment_intent.created",
    "payment_intent.payment_failed",
    "payment_intent.requires_action",
    "payment_intent.succeeded"
  ],
  "teams": [
    "channel.created",
    "channel.deleted",
    "channel.updated",
    "chat.created",
    "chat.deleted",
    "chat.updated",
    "chat_message.created",
    "chat_message.deleted",
    "chat_message.updated",
    "member.created",
    "member.deleted",
    "member.updated",
    "message.created",
    "message.deleted",
    "message.updated",
    "reply.created",
    "reply.deleted",
    "reply.updated",
    "team.deleted",
    "team.updated"
  ],
  "zendesk": [
    "organization.created",
    "organization.deleted",
    "organization.updated",
    "ticket.created",
    "ticket.deleted",
    "ticket.updated",
    "user.created",
    "user.deleted",
    "user.updated"
  ]
} as const satisfies Record<
  string,
  readonly string[]
>;

export const ADAPTERS_WITHOUT_KNOWN_TRIGGERS = [
  {
    "packageName": "@relayfile/azure-blob",
    "packagePath": "packages/azure-blob",
    "provider": "azure-blob",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/box",
    "packagePath": "packages/box",
    "provider": "box",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/adapter-docker-hub",
    "packagePath": "packages/docker-hub",
    "provider": "docker-hub",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/dropbox",
    "packagePath": "packages/dropbox",
    "provider": "dropbox",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/gcs",
    "packagePath": "packages/gcs",
    "provider": "gcs",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/gmail",
    "packagePath": "packages/gmail",
    "provider": "gmail",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/google-drive",
    "packagePath": "packages/google-drive",
    "provider": "google-drive",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/adapter-granola",
    "packagePath": "packages/granola",
    "provider": "granola",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/adapter-notion",
    "packagePath": "packages/notion",
    "provider": "notion",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/onedrive",
    "packagePath": "packages/onedrive",
    "provider": "onedrive",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/postgres",
    "packagePath": "packages/postgres",
    "provider": "postgres",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/redis",
    "packagePath": "packages/redis",
    "provider": "redis",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/s3",
    "packagePath": "packages/s3",
    "provider": "s3",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/sharepoint",
    "packagePath": "packages/sharepoint",
    "provider": "sharepoint",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  },
  {
    "packageName": "@relayfile/adapter-x",
    "packagePath": "packages/x",
    "provider": "x",
    "reason": "No supportedEvents() implementation and no mapping.yaml webhooks block"
  }
] as const;

export type KnownProviderName = keyof typeof KNOWN_TRIGGER_CATALOG;
export type KnownTriggerName<P extends KnownProviderName> =
  (typeof KNOWN_TRIGGER_CATALOG)[P][number];
